spring:
  application:
    name: order

server:
  port: 8082

menu:
  base-url: ${MENU_BASE_URL:http://menu:8081}
  timeout-ms: ${MENU_TIMEOUT_MS:2000}

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  rabbit:
    exchange: order.events
    queue: order.notifications
    routing-key: order.status.changed
