services:
  mongo:
    image: public.ecr.aws/docker/library/mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: public.ecr.aws/docker/library/rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  menu:
    build:
      context: .
      dockerfile: services/menu/Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/menu
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: "5672"
    depends_on:
      - mongo
      - rabbitmq

  order:
    build:
      context: .
      dockerfile: services/order/Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/order
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: "5672"
    depends_on:
      - mongo
      - rabbitmq

volumes:
  mongo_data:
