services:
  mongo:
    image: public.ecr.aws/docker/library/mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 })" ]
      interval: 5s
      timeout: 3s
      retries: 30

  rabbitmq:
    image: public.ecr.aws/docker/library/rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  menu:
    build:
      context: .
      dockerfile: services/menu/Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_MONGODB_URI: mongodb://mongo:27017/menu
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,env,configprops,loggers
      MANAGEMENT_ENDPOINT_ENV_SHOW_VALUES: ALWAYS
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: "5672"
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  order:
    build:
      context: .
      dockerfile: services/order/Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_MONGODB_URI: mongodb://mongo:27017/order
      MENU_BASE_URL: http://menu:8081
      MENU_TIMEOUT_MS: "2000"
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,env,configprops,loggers
      MANAGEMENT_ENDPOINT_ENV_SHOW_VALUES: ALWAYS
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: "5672"
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_started

volumes:
  mongo_data:
